### ISSUE TITLE
Change event not firing

### ISSUE THREAD

**Issue by alexdunne** [indrimuska/angular-moment-picker#126] opened 2017-02-08 12:08 UTC
Hey, I've been using the date picker and have run into a problem with the change event. As you can see from [this example](http://plnkr.co/edit/Y9sigSLVIGOw8iYD6xMy?p=preview), the change callback provided is not being called. 

Not sure if I've misunderstood the docs or if this is an actual bug.

Angular version: 1.5.8
Angular moment picker version: 0.9.5
Momentjs version: 2.10.6

**Comment by DickSwart** [comment] 2017-02-08 12:42
Same issue here, I'm using ControllerAs syntax thought that might be the issue. But now I see @alexdunne has the same issue

**Comment by adrian410** [comment] 2017-02-18 13:49
Same issue here.

**Comment by indrimuska** [comment] 2017-02-18 14:46
Hi guys, thank you for reporting this.
Not sure to understand the problem, since I see the callback has been fired when the model changes.

![image](https://cloud.githubusercontent.com/assets/1561134/23093989/0b457bbe-f5f1-11e6-8bfa-37a530ae0be9.png)


Actually, I observe a different issue. The formatted model (e.g., `firstDate`) won't be updated if the `ngModel` property has not been set. Already looking for a solution.

**Comment by fireole** [comment] 2017-02-19 05:02
Mine seems to get into the change event that I have defined, however the newValue, oldValue are undefined.

Angular version: v1.6.1
Angular moment picker version: 0.9.5
Moment version: 2.17.1

here is my markup:

![image](https://cloud.githubusercontent.com/assets/985103/23099480/94cfb1e0-f625-11e6-9a86-9303fff4552b.png)

here is my console debugger:

![image](https://cloud.githubusercontent.com/assets/985103/23099477/7944749c-f625-11e6-9ab1-89ccbea047b0.png)

**Comment by indrimuska** [comment] 2017-02-19 12:56
Hi @fireole, to help you I need the entire setting of your property (e.g., what's the value of `vm.data.statDate` and `vm.startDate`?) or -recommended- a full working example showing this issue.

**Comment by gsonego** [comment] 2017-02-21 10:28
Hi, same problem here.. I had to use version 0.94 to make this work.

**Comment by LousyJohnny** [comment] 2017-02-24 07:23
Same here : couldn't make it work with the latest release.
No error in the log. Works great with 9.4.

**Comment by mikeover** [comment] 2017-02-25 03:20
+1

**Comment by indrimuska** [comment] 2017-02-26 17:08
Sorry guys for coming back to you so late, my spare time becomes every time more smaller.
Anyway, I was be able to reproduce this issue and I think I've already fixed it. I've just released [v0.9.7](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.9.7) for this purpose. Please check it out and tell if it still persist. :)

I've also updated the README file adding a sample for (almost) each property. You can see the one regarding the `change` property in the [Events](https://github.com/indrimuska/angular-moment-picker/blob/master/README.md#events) section.
Thanks.

**Comment by creativedeveloper-net** [comment] 2017-03-03 14:05
Hi, looks like there is still some issue, but maybe in this concrete example:
[plunker](https://plnkr.co/edit/IWNP2P6qfjJs3ZBPnP5R?p=preview)
what I'm trying to achieve is a time-picker where I would like to be able to only select hours, and if neccessary I would like to change minutes manualy, but when I set max-view="day" it looks like it doesn't fire change event when I update input manualy

**Comment by indrimuska** [comment] 2017-03-14 17:39
Good analysis @creativedeveloper-net! Thank you for creating a full working example that's able to reproduce your issue. I'm going to look at this.

**Comment by indrimuska** [comment] 2017-03-14 18:02
It should be fixed in the latest commit and will be available in the next release in the next 2 days.

**Closed** 2017-03-18 01:39 UTC

**Comment by indrimuska** [comment] 2017-03-18 01:43
Latest release [v0.9.8](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.9.8) is now out.
