### ISSUE TITLE
Old value is not clearing

### ISSUE THREAD

**Issue by sadashivm** [indrimuska/angular-moment-picker#77] opened 2016-11-08 11:44 UTC
in bellow screen 1 first i selected date.
=> SCREEN 1
![1](https://cloud.githubusercontent.com/assets/10355473/20097760/269a4158-a5d6-11e6-824b-d7067b4df32e.png)

then later i cleared the textbox again if i click then it is showing old value. why it is not clearing old value

=> SCREEN 2
![2](https://cloud.githubusercontent.com/assets/10355473/20097767/2bf18b20-a5d6-11e6-9ed6-577bd79e633b.png)

**Comment by indrimuska** [comment] 2016-11-09 21:53
Hi @sadashivm, thanks for reporting this.
I've just verified this issue and, as you said, the directive does not clear the previous value in the picker view. I'm going to fix this as soon as I can :)

**Comment by indrimuska** [comment] 2016-11-17 22:58
Hi @sadashivm, can you please verify if you still have this issue in the [latest release](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.7.1).
Thanks.

**Comment by indrimuska** [comment] 2016-11-27 11:12
I'm going to close this issue, since I am no more able to reproduce it in the latest version.
Feel free to reopen it for any other trouble :)

**Closed by indrimuska** 2016-11-27 11:12 UTC
Labels: bug

**Comment by sadashivm** [comment] 2016-11-29 11:14
you are awesome man, its working fine , it is one of the best angular datepicker.
keep it up

**Comment by indrimuska** [comment] 2016-12-02 19:21
Thank you @sadashivm! 👍
