### ISSUE TITLE
Change event is sometime fired unnecessarily

### ISSUE THREAD

**Issue by vedard** [indrimuska/angular-moment-picker#53] opened 2016-08-31 02:18 UTC
Hi @indrimuska,

The issue happens when I first load the page, fetch my data then fill the model. The change event is fired after every page load.

``` javascript
$scope.$watch('value', function (value, previous) {
				if (!angular.isDefined($scope.valueMoment)) return;
				var oldValue = $scope.model,
					newValue = $scope.valueMoment.format($scope.format);
				if (newValue != oldValue)
					$timeout(function () {
						$scope.view.update($scope.view.moment = $scope.valueMoment.clone());
						$scope.model = newValue;
						if (angular.isFunction($scope.change))
							$timeout(function () {
								$scope.change({ newValue: newValue, oldValue: oldValue });
							}, 0, false);
					});
			});
```

In this [code](https://github.com/indrimuska/angular-moment-picker/blob/master/src/angular-moment-picker.js#L624), you compare the newValue with the oldValue as string, but sometime this code compare `"2016-07-29 06:50:00-04:00"` and `"2016-07-29T10:50:00Z"`. Since, they are different string it fired the change event.

I propose that you compare directly the date object, like in my example below, to solve this problem (in my case it now work fine):

``` javascript
if ($scope.valueMoment.valueOf() != moment(oldValue).valueOf())
```

**Comment by indrimuska** [comment] 2016-09-11 11:09
Hi @vedard, sorry for the late response.
Well, because of how Angular works, every time in the first $digest cycle it fires all $watch callbacks. You can check out this behavior [in this simple plunker](http://plnkr.co/edit/Xif7Nj43sl1YpnqxbxSZ).

Anyway that's not a really big problem, you can just check if the `newValue` is defined and is different from the `oldValue`:

```javascript
$scope.onChange = function (newValue, oldValue) {
	if (!angular.isDefined(newValue) || angular.equals(newValue, oldValue)) return;
	// perform your stuff...
};
```

**Comment by indrimuska** [comment] 2016-10-18 18:46
Hi @vedard, your problem will be solved (by design) in the next major release of the directive.
It will have a big breaking change (it will work with Moment Object instead of formatted moment strings) and if you are interested in it, you can have a look at https://github.com/indrimuska/angular-moment-picker/issues/60#issuecomment-254596657.

Anyway, I'm going to close this issue. Feel free to open it again if you'll still have any trouble.
Thanks :)

**Closed by indrimuska** 2016-10-18 18:46 UTC
