### ISSUE TITLE
Don't mutate underlying model

### ISSUE THREAD

**Issue by AgDude** [indrimuska/angular-moment-picker#60] opened 2016-09-16 14:04 UTC
The moment-picker directive actually changes the value on the scope into a string, and creates a new moment object as the `valueMoment` on the isolated scope. This means that while it provides a  nice UI, it can't actually be used for data binding, since it destroys the underlying model.

As a data input directive ngModel should be used for interacting with the user provided data.

**Comment by kroltan** [comment] 2016-09-20 11:47
It would be great to follow `ng-model` semantics indeed! This also means that `ng-change` and friends will work automatically, in addition to data-binding correctly.

**Comment by AgDude** [comment] 2016-09-20 13:30
This plunker references a fork of moment-picker that uses ngModel: http://plnkr.co/edit/0lTLqoh5JSlj26Nsnpf4?p=info

Note that there are some other changes in that fork, including a dependency on ui-bootstrap.

**Comment by indrimuska** [comment] 2016-09-20 23:19
Hi all. Actually this is not an issue, just a choice of design.
Anyway, I'm going to update *Angular Moment Picker* to support strings or Moment objects.
To preserve backward compatibility, when `format` property will be leave blank (at the moment this is a required property) it means that the model will be a Moment Object instead of a formatted String.

**Comment by rohdef** [comment] 2016-10-13 20:49
"Have you used it in anger, yet?", it's a way to test a things durability and usability. When people use or try something new they all go "ooooh" and like it. The real test comes when it is used in anger, when you got a deadline over your head, your boss is shouting at you for being late etc.

We probably all know the situation and the frustrations. For that reason components and APIs should work as people expect. When one throws out the uib date components because they suck and find this project, the anger is already at high levels. When at high levels of anger one do not want to spend time reading documentation because things behave differently than expected. And one do not want to spend time on finding ways to work around a model that is mutated unexpectedly.

What is wanted is to do ng-repeat over a model, adding datepickers, binding the date part of the model to the picker and to get nice moment objects back. This was my usage in anger not long ago. A component I should've had working in 10 minutes took me over 30 and is still not working. From reading the issues I suspect that this is exactly the one making my headache worse.

So when you say that this is not an issue, my response is: have you used it in anger, yet? Of course you know your own component quite well, but I suspect you've also tried using frameworks in anger, probably many times, if so you have also tried being where I an right now. If not, I envy you :) So here you also find a very good reason why you should use the ng-model approach and why the underlying model should not be mutated. A general advice is, never deviate from what people expect and want, unless, you have a very good reason, and even then consider it carefully :)

**Comment by indrimuska** [comment] 2016-10-13 21:04
Hi @rohdef, I understand your point view. However, the intended purpose of this direct was to work with Moment object in order to return strings. I understand that this may not follow *your expected behavior*, but this choice of design shouldn't be an issue if this is how the directive was born!  :)

Anyway, as I said, I'm going to support even this feature. Actually I am working during my spare time on my `return-moment-object`, and when everything will works it will be merged in the `master` branch.

**Comment by indrimuska** [comment] 2016-10-18 18:28
For those who are interested in this issue, I've created a plunker that uses my `return-moment-object` branch to make the directive work with Moment Objects instead of Strings.

Any feedback is welcome! :)

http://plnkr.co/edit/7k4QM63u6xU8EdzhUPHU?p=preview

**Notes:**
- This will be a breaking change for the project and will generate a new major version
- The model will be set by the `ng-model` attribute (`moment-picker` attribute does not require any value anymore)
- It will introduce the *Moment Picker Filter* to allow you to work with Moment Object even in your view templates (i.e. `<p>{{ myDate | momentPicker:'format':'YYYY-MM-DD' }}</p>`). It is basically a wrap filter that calls Moment.js methods (i.e. `format`) over the input objects (i.e. `myDate`).
- `format` property will remain in order to have an appropriate `$viewValue` when used with form input fields. Also, it could be useful to automatically retrieve `minView`/`maxView` values
- `minDate` and `maxDate` can be defined as string (in the same format defined by the `format` property, if set) or as Moment objects. It simplifies the way to update that values (if you use Moment.js methods).

**Comment by tartillo** [comment] 2016-11-21 19:37
Hi @indrimuska ,
First impression is quite okay, but when I test your plunker code, the locale formatting loads okay but is not used after updating the value with the picker.
Hope this helps.

HTML:
```
<div class="dropdown form-group">
    <label for="dateRangeStart">Van</label>
        <div class="input-group date">
            <input moment-picker format="dddd D MMMM YYYY" id="dateRangeStart" class="form-control" ng-model="dateRangeStart">
            <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
        </div>
    </a>
</div>

[...]

<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.16.0/moment.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.16.0/locale/nl-be.js"></script>
<!-- <script src="//cdn.rawgit.com/indrimuska/angular-moment-picker/master/dist/angular-moment-picker.min.js"></script> -->
<script src="//rawgit.com/indrimuska/angular-moment-picker/return-moment-object/src/angular-moment-picker.js"></script>
<script src="static/js/myapp.js"></script>
```

**Comment by tartillo** [comment] 2016-11-24 21:26
And the following error when locale is explicitly set (to 'nl') in defaults or within directive:

```
Error: a._locale is null
pb@http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.16.0/moment.min.js:212:183
ob@http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.16.0/moment.min.js:210:274
rb@http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.16.0/moment.min.js:217:160
sb@http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.16.0/moment.min.js:217:194
a@http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.16.0/moment.min.js:6:199
MomentPickerDirective.prototype.link/$scope.utility.valueToMoment@http://rawgit.com/indrimuska/angular-moment-picker/return-moment-object/src/angular-moment-picker.js:172:13
MomentPickerDirective.prototype.link/<@http://rawgit.com/indrimuska/angular-moment-picker/return-moment-object/src/angular-moment-picker.js:666:25
```
Hope this helps.

**Comment by indrimuska** [comment] 2016-11-27 11:33
Hi @tartillo, thank you for your feedbacks!
Let me answer to your question step-by-step:

1. `format` property is used for the input model view: updating that value, will update the format the date will be shown inside the field
2. I am unable to reproduce this issue, [this is the plunker](https://plnkr.co/edit/PD0HSDBAkshkPlOov2LO?p=preview) I've tested.

**Comment by tartillo** [comment] 2016-11-27 11:58
Hi @indrimuska, thanks!
Mistake is on my part (or moment.js). I didn't include the full `moment-with-locales.js` but only the `nl-be.js` locale. Apparently moment.js doesn't turn to that one when specifying simply 'nl' as locale.
The "issue" can be reproduced in your plunker by replacing your line:
```
<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment-with-locales.js"></script>
```
with:
```
<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.16.0/moment.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.16.0/locale/nl-be.js"></script>
```
Anyways, thanks for looking into it. You can just ignore :)

**Comment by indrimuska** [comment] 2016-11-27 12:39
Glad to hear you've solved your problem! :)

**Comment by indrimuska** [comment] 2016-11-29 00:02
Move to #91.

**Closed by indrimuska** 2016-11-29 00:02 UTC
Labels: enhancement
