### ISSUE TITLE
Custom position for the popup

### ISSUE THREAD

**Issue by george-i** [indrimuska/angular-moment-picker#78] opened 2016-11-08 14:05 UTC
Would be nice to have the option to position the popup (ex: left, top, right,bottom).
Or even better, to position itself to be visible when getting out of view.

**Comment by indrimuska** [comment] 2016-11-09 21:55
Hi @george-i, the directive already support dynamic position depending on the field position event during scroll. Maybe, you are facing a problem I am not able to reproduce, so can you please provide a valid example that shows this behavior?
Thanks

**Comment by yashvekaria** [comment] 2016-11-10 13:30
HI @george-i , I was seeking for position flags, through which we can set out datepicker popup as per our will. Have a look this link and you get the rest of the idea. 


[http://dbushell.github.io/Pikaday/examples/positions.html](http://dbushell.github.io/Pikaday/examples/positions.html)

**Comment by indrimuska** [comment] 2016-11-14 19:22
I'm going to close this issue, since Angular Moment Picker already support dynamic position of the picker based on the position of the input on the screen.

**Closed by indrimuska** 2016-11-14 19:22 UTC

**Comment by george-i** [comment] 2016-11-16 09:52
My problem was that the picker was in a Angular Material dialog and when opened, the picker was cut off by the modal. Eventually I've added a few CSS lines to fit my needs.
