### ISSUE TITLE
Error if specified locale attribute

### ISSUE THREAD

**Issue by simonemazzoni** [indrimuska/angular-moment-picker#111] opened 2017-01-11 18:27 UTC
Hi @indrimuska ,
I tried to specify the `locale` attribute in my input but it gives me this error.

`TypeError: Cannot read property 'longDateFormat' of null`

`ng-model="vm.scheduleDate" moment-picker="vm.scheduleDate"` these are the relevant parameters of the input. Notice that if I do not specify the locale attribute, the error isn't fired, but then if I change moment locale with `moment.locale("it")`, it changes only the name of the months and not the name of the week days.

Why? Am I missing something?

Simone

**Comment by indrimuska** [comment] 2017-01-13 21:54
Hi @simonemazzoni, maybe there's something wrong in your settings 'cause it seems to work properly to me.

```html
<input moment-picker="myDate" format="YYYY-MM-DD" locale="en">
```

Can you please share a working example of your configuration?
Thanks :)

**Comment by SimonGoransson** [comment] 2017-01-15 11:41
I have exactly the same problem, locale="en" works fine but "dk", "sv", "it" doesn't work for me.

**Comment by indrimuska** [comment] 2017-02-03 19:34
I'm going to close this issue since no answers has been provided.

**Closed by indrimuska** 2017-02-03 19:34 UTC

**Comment by simonemazzoni** [comment] 2017-02-03 21:17
@indrimuska yes, I'm sorry about this, but I hadn't time to investigate and I had to change library because of this bug and another issue about the responsiveness of the layout of the component.

**Comment by alexandredumat** [comment] 2018-02-24 12:57
The issue should be reopened, after 2 days of investigation wondering why the behavior of your component was buggy i finally nailed it !

There is a bug with the double binding on ng-model when locale is set to anything OTHER THAN "en" you can try for example "fr" !
Moreover you need to remove the format="YYYY-MM-DD" property that some how forces back the component to locale="en" thus preventing the error.

Very easy to reproduce :
> open your plunker https://embed.plnkr.co/hs10SM
> change locale="en" to locale="fr"
> remove format="YYYY-MM-DD"
> click on "set to today" you'll see that it set date to undefined or null

This makes the plugin impossible to use for any other language than English, and i hope that with this steps to reproduce it you'll be able to patch it (I tryed to look at your code but didn't manage to find any hint of solution).

Since the issue is closed and pretty old i'm going to open a new one on this
