### ISSUE TITLE
Angular 1.3.2

### ISSUE THREAD

**Issue by NanaPhil** [indrimuska/angular-moment-picker#68] opened 2016-10-08 07:52 UTC
Hello please does the library work with this version  Angularjs 1.3.2

**Comment by indrimuska** [comment] 2016-10-13 20:42
Hi @NanaPhil, could you please tell me the issues with this version of Angular? Do you have any feature that is not working to you?

**Comment by NanaPhil** [comment] 2016-10-14 11:39
Ok. I'm working on a project which i included this package . and the
controls seems to be disabled when i try to use it.

**Comment by alecbenson** [comment] 2016-10-18 16:59
Also having this issue.

**Comment by indrimuska** [comment] 2016-10-18 17:22
Thank you guys, could you please provide me a little plunker so I can work for a solution? :)
Thanks!

**Comment by NanaPhil** [comment] 2016-10-20 10:48
https://plnkr.co/edit/PozXQeW0eHdVxxIfgpeT?p=preview

**Comment by conradwarhol** [comment] 2016-10-20 14:00
Also having this issue with angularjs v1.3.15

**Comment by indrimuska** [comment] 2016-10-20 15:10
Well, got it! The problem is due to how Angular sets scopes variables, in particular them used with fn binding. Indeed even if you haven't set the Moment Picker property `selectable`, you'll get that property set in the controller.

The fix is very simple, I'm going to pack a solution and a new release as soon as I can. :)
Thank you all for reporting this.

**Comment by indrimuska** [comment] 2016-10-20 18:32
I've just released [v0.6.7](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.6.7) that contains this fix for Angular 1.3.
Thank you guys, good work! :)

**Comment by ghostrydr** [comment] 2017-03-07 01:26
Looks like this is still an issue with the latest version of moment picker and Angular 1.3.*

https://plnkr.co/zCpgQK

If you bump the angular version to 1.4 it starts working.

**Comment by indrimuska** [comment] 2017-03-07 08:02
Thank you @ghostrydr for reporting this, I"ll look into this.

**Comment by indrimuska** [comment] 2017-03-18 02:11
Ok, got it! Angular 1.3 returns handles function binding properties using `angular.noop` function when no values are provided. In this case, `selectable` is always fired returning an undefined value (noop does nothing). Since it's not returning true, you see no cell is selectable.

**Comment by indrimuska** [comment] 2017-03-18 02:17
Fixed in [v0.9.9](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.9.9).

**Closed** 2017-03-18 02:16 UTC
