### ISSUE TITLE
Initialize formatted datetime on load

### ISSUE THREAD

**Issue by Yugloocamai** [indrimuska/angular-moment-picker#146] opened 2017-03-13 22:28 UTC
Why doesn't this directive render the formatted datetime on init?  There doesn't seem to be any simple way of doing this.  This should be default behavior.  Render datestring provided in "moment-picker" on init.

**Comment by indrimuska** [comment] 2017-03-17 23:47
Hi @Yugloocamai, let me find a way to simplify this process...

**Comment by indrimuska** [comment] 2017-03-17 23:52
In the next release this should be fixed.

```html
<div ng-init="ctrl.stringDate = '2017-01-20';">
    <input class="form-control"
           placeholder="Select a date..."
           moment-picker="ctrl.stringDate"
           format="YYYY-MM-DD"
           ng-model="ctrl.momentDate"
           ng-model-options="{ updateOn: 'blur' }">
    <!-- ctrl.momentDate is undefined -->
</div>
```

**Closed** 2017-03-18 01:39 UTC

**Comment by indrimuska** [comment] 2017-03-18 01:45
Latest release [v0.9.8](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.9.8) is now out.

**Comment by roberteles** [comment] 2017-03-25 16:40
Hello Indri,

Thanks for this fantastic date picker - I feel it's one of the best ones out there.

To offer you a little bit of context, I believe that most people developing applications prefer keeping one standard regarding time, which is the ISO8601 format (eg. 1980-12-20T00:00:00.000Z). There are many libraries out there which can format this for viewing purposes, hence the popularity of it.

I think that the expectation of many of my other fellow colleagues, including mine, is that when they pass a variable to your date picker, they expect it to be read automatically, and then display it in the format specified, but still keeping the actual model data in the initial ISO8601 way.

For example, if `vm.dob = 1980-12-20T00:00:00.000Z`, then `<input moment-picker="vm.dob" format="MM-DD-YYYY">` should display the data as `12-20-1980`, without having to manually format the string variable in the controller, or set the vm.dobModel to be equal to `moment()`. Then, when one would check vm.dob after the date-picker loaded, it would still be `1980-12-20T00:00:00.000Z`.

The ultimate goal with this is to be able to control the format the data is displayed, while the model/data in itself maintains the ISO8601 format, and when sending that data back to the server, there is no extra formatting that needs to be done.

I believe that this works automatically with the 'YYYY-MM-DD' format, but I can confirm that it is not working with 'MM-DD-YYYY', since moment.js doesn't know how to pick it up, and it forces us to pre-format the text to `MM-DD-YYYY`, pass it to `moment-picker` and then reformat it to ISO8601 before sending it to the API, which is a cumbersome experience, it involves adding more code to controllers, when I think it can be nicely solved in the component.

Best,
Robert
