### ISSUE TITLE
Picker date selection confused in IE

### ISSUE THREAD

**Issue by GeorgeKnap** [indrimuska/angular-moment-picker#132] opened 2017-02-20 15:01 UTC
This might be a bit of odd use-case but anyway. Problem occurs only in .NET Forms WebBrowser Control which uses IE to render.  Any other browsers works fine (tested on Chrome, Edge, Safari). Lets look at the screen video:
[http://giphy.com/gifs/angular-moment-picker-xTiN0zgljEJo5NzALS](http://giphy.com/gifs/angular-moment-picker-xTiN0zgljEJo5NzALS)

The picker opens the popup calendar at correct datetime but fails to update the datetime on selection. I have even put scope.watch into my code to see how the bound moment object changes but the watch never triggers.

this is my html:
```html
<div class="input-group">
    <span class="input-group-addon">
        <i class="fa fa-clock-o" aria-hidden="true"></i>
    </span>
    <input class="form-control input-sm"
           name="dataFrom"
           placeholder="Select a time"
           data-ng-model="ctrl.data.dataFrom"
           data-ng-model-options="{ updateOn: 'blur' }"
           data-moment-picker="ctrl.data.labelDataFrom"
           data-locale="{{ctrl.data.momentPickerLanguage}}"
           data-format="LLL"
           data-min-view="year"
           data-max-view="hour"
           data-start-view="day"
           data-min-date="ctrl.data.minDate"
           data-max-date="ctrl.data.maxDate"
           data-today="true">
</div>
```

These are the controller's data:
```js
this.data = {
    dataFrom: moment().subtract(1, 'days'),
    dataTo: moment(),
    minDate: moment().subtract(1, 'years').format('LLL'),
    maxDate: moment().format('LLL'),
    labelDataFrom: moment().subtract(1, 'days').format('LLL'),
    labelDataTo: moment().format('LLL'),
    momentPickerLanguage: this.$translate.use()
};
```

The issue started happening after upgrading from version 0.8.4 to version 0.9.x. Currently at the latest 0.9.5
No console errors being logged.

Any ideas?
Cheers

**Comment by indrimuska** [comment] 2017-02-26 21:00
Hi @GeorgeKnap, I'm not able to reproduce this issue. Just tested on IE11.

![image](https://cloud.githubusercontent.com/assets/1561134/23343623/f8e72cf4-fc6e-11e6-89fe-b369c561ec40.png)

This is the Plunker I've created to analyze this issue:
https://plnkr.co/edit/EVp1IL?p=preview

**Comment by indrimuska** [comment] 2017-03-14 18:26
Closing this since it's not reproducible.

**Closed by indrimuska** 2017-03-14 18:26 UTC
