### ISSUE TITLE
Weird behavior with bootstrap dropdown

### ISSUE THREAD

**Issue by yiwenliuable** [indrimuska/angular-moment-picker#101] opened 2016-12-19 22:04 UTC
Hi I just found this angular-moment-picker and it works great! In my project I use this moment-picker with bootstrap dropdown, and there are some issues I found:

- Issue 1:
Without angular ngAnimate, the moment-picker menu will automatically close after selecting "month", and no date is selected. It closes dropdown as well.
Plunker: https://plnkr.co/edit/0dUgDJyjNu71h2919KVl?p=preview

- Issue 2:
With angular ngAnimate, I can successfully select a date but it not only close the moment-picker menu but also close the dropdown as well.
Plunker: https://plnkr.co/edit/uK495hxgp6XFDHAOad0l?p=preview

I am looking for a solution for issue 2. 
In my dropdown-menu, I also provide a submit button, so after selecting a date I don't want the dropdown to be closed automatically.
For now I need to listen to the change event, and open the dropdown again.

Any help is appreciated!

angular-moment-picker version:
tag 0.8.3 (but in the script it says v0.8.2)

**Comment by indrimuska** [comment] 2016-12-20 18:50
Hi @yiwenliuable, keeping outside my personal thoughts about using nested dropdown :), I think your issue is caused by `uib-dropdown` directive when someone clicks on the picker.

Since you have chosen to set the autoClose option to `outsideClick`, he thinks that someone has clicked outside its content, that is naturally wrong. More weird is that Moment Picker directive does not propagate click event (to be specific it does not propagate mousedown event), so I don't know how could it think that someone has clicked outside.

Anyway, I think that if you want to add more elements to your dropdown content you need to manually handle opening/closing it, especially if you want to do that after a submit action. This way you can use the `is-open` property given by ui-dropdown directive.

**Comment by indrimuska** [comment] 2016-12-28 18:31
@yiwenliuable in the latest release I've added a new property that may help you: `isOpen` will let you open/close the picker programmatically.
Anyway, I'm going to close this issue, but feel free to ping me if you find a way to fix this or you have any other trouble related to this.
Thanks! :)

**Closed by indrimuska** 2016-12-28 18:31 UTC
