### ISSUE TITLE
min-view="day" - cannot change the "day" value from controller. It takes current date as default.

### ISSUE THREAD

**Issue by jeyarajcs** [indrimuska/angular-moment-picker#123] opened 2017-02-02 19:25 UTC

**Comment by indrimuska** [comment] 2017-02-02 23:38
Hi @jeyarajcs, I'm not sure to reproduce your issue.
Can you please share an example of usage or a plunker that show this issue?

**Comment by jeyarajcs** [comment] 2017-02-03 17:35
```
<div class="input-group" moment-picker="scheduledata.start_time" 
           format="LT" 
           min-view="day"
           autoclose="true">
<input class="form-control" id="timing" placeholder="select time" 
        ng-model="scheduledata.start_time" 
        ng-model-options="{ updateOn: 'blur' }" 
        autocomplete="off">
</div>
```
Hi @indrimuska , actually that is not an issue. Just an additional requirement. In the above code i used min-view="day".  That takes current date as default. Is there any possibility  to change the date value from controller?  I attached image, in that I highlighted the date like "February 3, 2017". That date  is automatically coming(system date), Instead of that can I manually load some date from controller?i.e("March 10, 2017). 

![image](https://cloud.githubusercontent.com/assets/13285081/22601382/a395e37e-ea64-11e6-9d35-adda865e9db7.png)

**Comment by indrimuska** [comment] 2017-02-03 19:31
Well, you are using format `LT`.
How can you specify the date in a controller using that format? Simply you can't, because that formats is just a representation of time (e.g., "8:30 PM", "20:18").

That being said, you have two ways:
 - *Remove header*: add `show-header="false"` as attribute and don't care about the displayed date, just use it as a time picker
 - *Use Moment.js objects*: setting ng-model in the same element of the directive will allow using Moment.js objects and formatted date string at the same time (check out README file for further infos).

**Comment by indrimuska** [comment] 2017-02-03 19:32
Anyway, I'm going to close this issue. Feel free to ping me for any doubt :)

**Closed** 2017-02-03 19:33 UTC

**Comment by jeyarajcs** [comment] 2017-02-04 05:56
Yah sure.. Thanks for your response..
